/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntriesIndexRouteImport } from './routes/entries.index'
import { Route as EntriesDateRouteImport } from './routes/entries.$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIndexRoute = EntriesIndexRouteImport.update({
  id: '/entries/',
  path: '/entries/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesDateRoute = EntriesDateRouteImport.update({
  id: '/entries/$date',
  path: '/entries/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entries/$date': typeof EntriesDateRoute
  '/entries/': typeof EntriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entries/$date': typeof EntriesDateRoute
  '/entries': typeof EntriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entries/$date': typeof EntriesDateRoute
  '/entries/': typeof EntriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entries/$date' | '/entries/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entries/$date' | '/entries'
  id: '__root__' | '/' | '/entries/$date' | '/entries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntriesDateRoute: typeof EntriesDateRoute
  EntriesIndexRoute: typeof EntriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/': {
      id: '/entries/'
      path: '/entries'
      fullPath: '/entries/'
      preLoaderRoute: typeof EntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$date': {
      id: '/entries/$date'
      path: '/entries/$date'
      fullPath: '/entries/$date'
      preLoaderRoute: typeof EntriesDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntriesDateRoute: EntriesDateRoute,
  EntriesIndexRoute: EntriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
